/* confdefs.h */
#define PACKAGE_NAME "mingw-w64-runtime"
#define PACKAGE_TARNAME "mingw-w64-runtime"
#define PACKAGE_VERSION "4.0b"
#define PACKAGE_STRING "mingw-w64-runtime 4.0b"
#define PACKAGE_BUGREPORT "mingw-w64-public@lists.sourceforge.net"
#define PACKAGE_URL ""
#define PACKAGE "mingw-w64-runtime"
#define VERSION "4.0b"
#define __ENABLE_GLOBBING -1
#define HAVE_CTOR_LIST 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
